services:
  pgc-perf-opt:
    image: yshebron/pgc-perf-opt
    ports:
      - "127.0.0.1:0:8787"
    environment:
      PASSWORD: rstudio
      ROOT: true
      DISABLE_AUTH: false
      DOCKER_RUNNING: true
    volumes:
      - ../benchmarks:/home/rstudio/pgc-perf-opt/benchmarks
      - ../code:/home/rstudio/pgc-perf-opt/code
      - ../data:/home/rstudio/pgc-perf-opt/data
      - ../results:/home/rstudio/pgc-perf-opt/results