services:
  pgc-base-cpu:
    image: yshebron/cpu
    ports:
      - "127.0.0.1:0:8787"
    environment:
      PASSWORD: yourpassword
      ROOT: true
      DISABLE_AUTH: false
      USERID: 1001
      GROUPID: 1001
    volumes:
      - ./benchmarks:/home/rstudio/pgc-perf-opt/benchmarks
      - ./code:/home/rtudio/pgc-perf-opt/code
      - ./data:/home/rstudio/pgc-perf-opt/data